use_frameworks!

platform :ios, '9.0'

target 'NumberRecognition_Example' do
  pod 'NumberRecognition', :path => '../'

  target 'NumberRecognition_Tests' do
    inherit! :search_paths

    
  end
end
